# Generated by Django 5.1.3 on 2024-12-04 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hairdresser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, чтобы скрыть элемент.",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
                ),
                (
                    "first_name",
                    models.CharField(max_length=256, verbose_name="Заголовок"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=256, verbose_name="Заголовок"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "slug",
                    models.SlugField(
                        help_text="Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.",
                        unique=True,
                        verbose_name="Идентификатор",
                    ),
                ),
            ],
            options={
                "verbose_name": "парикмахер",
                "verbose_name_plural": "Парикмахеры",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, чтобы скрыть элемент.",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
                ),
                ("title", models.CharField(max_length=256, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "pub_date",
                    models.DateTimeField(
                        help_text="Если установить дату и время в будущем — можно делать отложенные публикации.",
                        verbose_name="Дата и время публикации услуги",
                    ),
                ),
                ("price", models.PositiveIntegerField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Изображение"
                    ),
                ),
            ],
            options={
                "verbose_name": "услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
        migrations.CreateModel(
            name="OrderedServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, чтобы скрыть элемент.",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлено"),
                ),
                (
                    "serve_date",
                    models.DateTimeField(
                        help_text="Если установить дату и время в будущем — можно делать записи к парикмахерам.",
                        verbose_name="Дата и время оказания услуги",
                    ),
                ),
                ("comment", models.TextField(verbose_name="комментарий")),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Получатель услуги",
                    ),
                ),
                (
                    "hairdresser",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hairdresser",
                        to="services.hairdresser",
                        verbose_name="парикмахер, оказывающий услугу",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service",
                        to="services.service",
                        verbose_name="оказываемая услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "заказанная услуга",
                "verbose_name_plural": "Заказанные услуги",
                "ordering": ("created_at",),
            },
        ),
        migrations.AddField(
            model_name="hairdresser",
            name="services",
            field=models.ManyToManyField(
                to="services.service", verbose_name="Предпочтения по парикмахерам"
            ),
        ),
    ]
