# Generated by Django 5.1.3 on 2024-12-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderedservices",
            name="payed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="hairdresser",
            name="first_name",
            field=models.CharField(max_length=256, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="hairdresser",
            name="last_name",
            field=models.CharField(max_length=256, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="hairdresser",
            name="services",
            field=models.ManyToManyField(
                to="services.service", verbose_name="Оказываемые услуги"
            ),
        ),
    ]
