# Generated by Django 5.1.3 on 2024-12-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_hairdresser_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderedservices",
            name="payed",
            field=models.BooleanField(default=False, verbose_name="цена"),
        ),
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.PositiveIntegerField(verbose_name="цена"),
        ),
    ]
