# Generated by Django 5.1.3 on 2024-12-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="hairdresser_preference",
            field=models.ManyToManyField(
                to="services.hairdresser", verbose_name="Предпочтения по парикмахерам"
            ),
        ),
    ]
