# Generated by Django 5.1.3 on 2024-12-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_useraccount_hairdresser_preference"),
        (
            "services",
            "0002_orderedservices_payed_alter_hairdresser_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="hairdresser_preference",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="services.hairdresser",
                verbose_name="Предпочтения по парикмахерам",
            ),
        ),
    ]
